# fly.toml file generated for meal-ideas-ui on 2023-04-18T11:56:28-04:00

app = "meal-ideas-ui"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "yyz"
processes = []

[env]
  API_BASE_URL="https://meal-ideas-backend.fly.dev/api"

[[services]]
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
